disease_abbrev <- c(
  "allergy" = "allergy",
  "Alzheimers disease" = "Alzheimers disease",
  "arthritis" = "arthritis",
  "asthma" = "asthma",
  "bipolar disorder" = "bipolar disorder",
  "cardiac arrhythmia" = "cardiac arrhythmia",
  "chronic obstructive pulmonary disease" = "COPD",
  "coronary heart disease" = "coronary heart disease",
  "drug dependence" = "drug dependence",
  "hypertension" = "hypertension",
  "multiple sclerosis" = "multiple sclerosis",
  "obesity" = "obesity",
  "Parkinson's disease" = "Parkinson's disease",
  "psoriasis" = "psoriasis",
  "rheumatoid arthritis" = "rheumatoid arthritis",
  "schizophrenia" = "schizophrenia",
  "stroke" = "stroke",
  "systemic lupus erythematosus" = "lupus",
  "type I diabetes mellitus" = "type I diabetes",
  "type II diabetes mellitus" = "type II diabetes",
  "ulcerative colitis" = "ulcerative colitis",
  "unipolar depression" = "unipolar depression"
)